### ISSUE TITLE
About issues on recent files

### ISSUE THREAD

**Issue by garamika** [OpenMLTD/MLTDTools#15]
It seems that the file structure on scrobj file has changed once - though the exact time is unsure.
For some songs MillionDance is able to translate the facial motions like blinking or winking to MMD near perfectly - especially for older songs (e.g. Jireru heart ni hi wo tukete) However for more recent songs (like Mirai Hikou, Kururiuta) the program only translates the lipsync.
Would you look over the structure of "scrobj" file so that the program can translate the file?
Thanks in advance.

**Comment by hozuki** [comment]
About facial expressions...
MLTD uses an internal "morph table" to indicate facial expressions. In the scrobj files, they put a "morph index" instead of storing the full morph animation (like in VMD). Unfortunately, MillionDance does not know about unseen facial expressions.
For example, if `morph 100` represents a laughter, but it is not seen before (suppose we only know about 1 to 99), MillionDance just outputs the default facial expression.
So my guess is that they just used new facial expressions. I need to check the file to confirm it.

If that is the reason, how to fix the problem? Hmm, it is complicated.

1. Find the moments when the model should show an expression but doesn't
2. Read the scrobj and find its morph index.
3. Reproduce the facial expression in other software, say, PmxEditor.
4. Enter the values in [TDFacial](https://github.com/OpenMLTD/MLTDTools/tree/master/src/TDFacial) and save the JSON file (`facial_expr.json`).
5. Now MillionDance can understand the facial expression.

Step 2 is the most complicated one, esp. for common users. I did this by hand and it is like a torture, because scrobj is a huge mess of many different kinds of data. I'll think a way to make the whole thing easier... :(

**Comment by hozuki** [comment]
It turns out that some scrobjs split their facial expressions: one set in the landscape view, the other in the portrait view. In previous files, there is only one set of facial expressions, located in the base scrobj.

So an option was added in MillionDance:

![image](https://user-images.githubusercontent.com/7345875/81629754-3056db00-9404-11ea-991a-603516bd6cd7.png)

Also a utility was added in TDFacial:

![image](https://user-images.githubusercontent.com/7345875/81629515-9d1da580-9403-11ea-8d9e-93b1cf133ea8.png)

Hope it helps to ease the pain.

But beware! It seems more facial expressions are added. This is the current state of default mapping file:

![image](https://user-images.githubusercontent.com/7345875/81629592-cc341700-9403-11ea-8002-810b7ab525a4.png)

I can't trace all of it so the user himself have to find out the specific morph values.

**Comment by hozuki** [comment]
Can you confirm that this problem is solved?

**Comment by garamika** [comment]
Sorry for late reply. This has been resolved and I forgot to comment.
I closed the issue.
