### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by LudoMako** [OpenMLTD/MLTDTools#27]
Was trying to rip overmaster(hmt030) and loaded miki's head(since it seems that if you don't use the same char that was meant for the song it won' export facials like blink or eyebrows) and it didn't export anything followed by this error 
Tried both latest release and unstable build(btw, thought special appeal was bundled with the main dance unity file, how would u have an external ap.imo.unity file?)
09:20:47 Error occurred.
09:20:47 System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in OpenMLTD.MillionDance.Core.PmxCreator.Physics.AppendSwayBones(PmxBone[] bones, SwayBone[] swayBones, List`1 bodies) in C:\projects\mltdtools\src\MillionDance\Core\PmxCreator.Physics.cs:riga 205
   in OpenMLTD.MillionDance.Core.PmxCreator.Physics.ImportPhysics(PmxBone[] bones, SwayController bodySway, SwayController headSway) in C:\projects\mltdtools\src\MillionDance\Core\PmxCreator.Physics.cs:riga 42
   in OpenMLTD.MillionDance.Core.PmxCreator.CreateModel(CompositeAvatar combinedAvatar, CompositeMesh combinedMesh, Int32 bodyMeshVertexCount, SwayController bodySway, SwayController headSway, ConversionDetails details, ValueTuple`2[]& materialList) in C:\projects\mltdtools\src\MillionDance\Core\PmxCreator.Model.cs:riga 69
   in OpenMLTD.MillionDance.FMain.DoWorkInternal(Object state) in C:\projects\mltdtools\src\MillionDance\FMain.Working.cs:riga 249
   in OpenMLTD.MillionDance.FMain.DoWork(Object state) in C:\projects\mltdtools\src\MillionDance\FMain.Working.cs:riga 28

**Comment by LudoMako** [comment]
Also tried both latest release and auto build, same error

**Comment by hozuki** [comment]
What are the exact models (head and body) are you using?

---

* Lip sync and facial expressions conversion do not require a model, only the scenario file. So they are applicable to all models.
* If there is no companion `_ap.imo.unity3d` just leave that field empty. When you select an appeal, MillionDance will attempt to load the internal appeals first, and then the external one if the previous one does not exist.

**Comment by LudoMako** [comment]
Cb ex 001, ch ex001 mik, then the scrobj is broken? Almost all the time
only the lip sync gets converted, no blinking, no moving eyebrows, because
the app itself says there were no keys like "can't find key 2, skipping and
using default emotion instead"
And sure, I will try with the appeal

Il ven 24 lug 2020, 11:27 hozuki <notifications@github.com> ha scritto:

**Comment by hozuki** [comment]
Hmm, I found the cause. There is a mismatch between the head [avatar](https://docs.unity3d.com/Manual/class-Avatar.html) and transform hierarchy. Some bones in the transforms (which are the actual objects that are moving when you play the game) are missing from the avatar. It looks like a mistake made by the artists. I'll rewrite the code of this part and it may take some time.

**Comment by LudoMako** [comment]
Thank you so much! The appeal also, works perfectly (I tried 3 songs)

Il ven 24 lug 2020, 12:17 hozuki <notifications@github.com> ha scritto:

**Comment by hozuki** [comment]
It should be fixed now.

Also, the scrobj of `hmt030` works fine according to my test. Eyes are acting normally, and known expressions are presented correctly.

The warnings are saying that MillionDance doesn't know what those facial expressions mean. To fix that, you can reproduce the facial expression by following these steps:

1. locate the missing expression keys and time points (displayed in the messages; times are in seconds);
2. watch the reference MV ([example](https://www.youtube.com/watch?v=e2J_b7DxNtQ), or just open the game);
3. edit morph weights in the config file (`facial_expr.json`) with TDFacial.

Sorry but there isn't a more convenience way to achieve that for now.

The issue is closed by [keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). It's okay to continue replying or reopen if needed.

**Comment by LudoMako** [comment]
I will try, will download the auto build

Il ven 24 lug 2020, 17:22 hozuki <notifications@github.com> ha scritto:
