### ISSUE TITLE
Sphere maps and cube maps

### ISSUE THREAD

**Issue by Sozuke** [OpenMLTD/MLTDTools#29]
I discovered that some models bring their sphere map textures and cubemaps (dress and accessory glow)
assetstudio doesn't export them, but utinyripper does

For example the kotoha dress
https://youtu.be/LkkjYK43jLs

**Comment by hozuki** [comment]
What is the difference without the cubemaps? Do you mean these?

![image](https://user-images.githubusercontent.com/7345875/89128268-ef4b0000-d4f4-11ea-86cc-37482bb0d5ce.png)

**Comment by Sozuke** [comment]
for some reason that kotoha dress has a spa but not cubemaps (they were exported in the same folder as the textures), but elena has cubemaps (they were exported in a folder called cubemaps), also, some objects refer to totally dark textures, not  I understand their purpose

**Comment by hozuki** [comment]
Hmm, this is why there is a "cubemap". The shader used in the model (`Custom_Chr_Basic`) has a parameter called "_Cube" with type `Cube` (which means cubemap in Unity Cg shaders). Its description is "reflection cubemap". So obviously(?) it is an envmap. Its default value is `"_Skybox"` which points to the skybox cubemap assigned in the scene. UtinyRipper must be intelligent enough to consider that as a resource reference and tries to find the referenced cubemap. Anyway, since we are using the default shaders provided by MMD/MMM, the cubemaps are not used.

**Comment by hozuki** [comment]
Some newer models (e.g. `cb_sr077_a`) also have cubemaps. But as I explained above cubemaps are not used in PMX materials. So I think we can close this issue for now.
Maybe there will be someone who use these models with cubemap-enabled MME shaders. Let's solve the issue then.
