### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by Tomori9n** [OpenMLTD/MLTDTools#32]
keep getting this errror when trying to export the "Hyakka wa Gekka ni Chirinuru wo" model, it only exports the head textures but not the body
https://files.catbox.moe/e1g6mh.PNG
https://files.catbox.moe/wnsd19.txt

**Comment by hozuki** [comment]
This model body uses a material `lambert` which is... well, basic Lambert material. The corresponding part of the mesh is the inner collar. (But this part is totally invisible... another mistake?)
It has a `_MainTex` parameter but that parameter does not reference any texture (it is a null pptr). So by default it should be using the `"white"` texture. Fixed in the next commit.
