### ISSUE TITLE
Textures?

### ISSUE THREAD

**Issue by animegamer89** [OpenMLTD/MLTDTools#8]
How do you get the textures to put on the models? Is this still being worked on or is there something missing that I'm doing?

**Comment by hozuki** [comment]
No you didn't miss anything. To apply textures, you need to export them using some tool (say, UABE, or Asset Studio), and put them in the right place. For "the right place" you can see referenced texture names in PMX Editor.

I haven't finished writing this part in the wiki yet. Because the method is inefficient: I haven't found a good way to map the textures in good order, so you have to a lot of trial-and-errors (like, which texture is texture01 and which is texture02). To prepare the models for demo I tried around 5 minutes for each model, and that was after I got familiar with some quick matching insights.

**Comment by animegamer89** [comment]
Got it! Thanks!

**Comment by hozuki** [comment]
Just a reminder... starting from commit 570b7263a3d9ae5de9b0735eb58f8cd23ef22259 (commited today), textures can be exported automatically. :)
