### ISSUE TITLE
Any plan on unsupported motions?

### ISSUE THREAD

**Issue by garamika** [OpenMLTD/MLTDTools#9]
Nowadays there are some unsupported motions on MillionDance like "White Vows" or "Rebellion" - in which they dont have files containing "imo" in the dance file name.
Do you have any plan on supporting these motions?
Best regards.

**Comment by hozuki** [comment]
Yes I think so. I just opened one (Rebellion) and it seems to be computed `AnimationClip`. This can be handled, because we have to generate this to convert to MMD system anyway.

A funny deduction is `*.imo` should be some kind of source file, used in development, but those guys put them in production resources. It is like leaking source code while you should only distribute binaries. 🤣

**Comment by garamika** [comment]
Thank you for the answer!

**Comment by Reona945** [comment]
Any Update on unsupported motions?

**Comment by garamika** [comment]
Sorry for late reply. This has been resolved and I forgot to comment.
I closed the issue.
